function r = GLeQ(sub, x, theta, phi, w, C)
% GLeQ.m
% Global Lebedev Quadrature
%
% Input:  sub,           4 subscripts of the 4th order tensor T, 1*4 matrix;
%         x,             3 semi-axes of an inclusion, 3*1 matrix;
%         thate, phi, w, nodes and weights generated by Lebedev(m);          
%         C,             stiffness of the matrix, 1*81 matrix;

% Output: r is the result of the numerical integration, a scalar;
%--------------------------------------------------------------------------
  w  = reshape(w, 1, []);
  theta = reshape(theta,1,[]);
  phi = reshape(phi,1,[]);
  x=x';
  r  = partTLeb(sub(1),sub(2),sub(3),sub(4),w,theta,phi,C,x);
% final results using Lebedev quadrature 
  r  = x(1)*x(2)*x(3)*r;
end

